### ISSUE TITLE
piui_demo.py works just for a while.

### ISSUE THREAD

**Issue by NikiGHz** [dps/piui#10]
Hello, I installed piui the do-it-yourself way. I configured the **init**.py file so it now uses directly port 80, buty I have to start the demo with sudo because normal users don't have permission to use port 80.
I did that to access piui just putting the Rasp IP on the browser.
The thing is, after I start the demo script, I am able to access the piui interface, but after pushing some buttons, it starts to get sticky, until it is completely unusable and I have to kill the executing code and run it again to be able to access.

I guess this is the normal whay piui do things:

When I start to run the script, it displays this on the terminal:
`pi@raspberrypi:/home/piui $ sudo python piui_demo.py
[17/Jul/2016:21:40:04] ENGINE Listening for SIGHUP.
[17/Jul/2016:21:40:04] ENGINE Listening for SIGTERM.
[17/Jul/2016:21:40:04] ENGINE Listening for SIGUSR1.
[17/Jul/2016:21:40:04] ENGINE Bus STARTING
[17/Jul/2016:21:40:04] ENGINE Started monitor thread 'Autoreloader'.
[17/Jul/2016:21:40:04] ENGINE Started monitor thread '_TimeoutMonitor'.
[17/Jul/2016:21:40:04] ENGINE Serving on http://0.0.0.0
[17/Jul/2016:21:40:04] ENGINE Bus STARTED`

It stays that way until I access piui, when I open piui, it starts to output this:
`192.168.1.100 - - [17/Jul/2016:21:40:50] "GET /static/app.html HTTP/1.1" 200 1924 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
192.168.1.100 - - [17/Jul/2016:21:40:50] "GET /static/jquery-1.9.0.min.js HTTP/1.1" 304 - "http://192.168.1.40/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
192.168.1.100 - - [17/Jul/2016:21:40:50] "GET /static/ratchet.css HTTP/1.1" 304 - "http://192.168.1.40/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
192.168.1.100 - - [17/Jul/2016:21:40:50] "GET /static/ratchet.js HTTP/1.1" 304 - "http://192.168.1.40/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
192.168.1.100 - - [17/Jul/2016:21:40:50] "GET /static/piui.js HTTP/1.1" 304 - "http://192.168.1.40/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
Page Reload 9/9`

After that, if I navigate on the site, it eventually starts to get stuck. 
- Sometimes, it takes some seconds to respond.
- The "Back" button stops working.
- Pages are loaded partially or take too long to respond.

I guess it is the same ploblem other dude reported.
I am using Raspbian Jessie on a Raspberry Pi 2.

I noticed that sometimes, when it gets unstuck, it outputs something different on the terminal:
`[17/Jul/2016:21:44:12] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/home/piui/piui/**init**.py", line 89, in click
    self._current_page_obj.handle_click(eid)
  File "/home/piui/piui/__init__.py", line 310, in handle_click
    button = self._clickables[eid]
KeyError: u'li_5303992264646282'

[17/Jul/2016:21:44:12] HTTP
Request Headers:
  REFERER: http://192.168.1.40/
  HOST: 192.168.1.40
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.100
  ACCEPT: _/_
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: es-ES,es;q=0.8
  ACCEPT-ENCODING: gzip, deflate, sdch
192.168.1.100 - - [17/Jul/2016:21:44:12] "GET /click?eid=li_5303992264646282 HTTP/1.1" 500 1492 "http://192.168.1.40/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[17/Jul/2016:21:44:12] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/home/piui/piui/**init**.py", line 89, in click
    self._current_page_obj.handle_click(eid)
  File "/home/piui/piui/__init__.py", line 310, in handle_click
    button = self._clickables[eid]
KeyError: u'li_6117838461521958'`

**Comment by avneesh1mehta** [comment]
^^^^^ I'm having the same issue
